data:
  base_path: 'data/'
  raw_data_path: 'iwslt15_en-vi'
  processed_path: 'processed_iwslt15_en-vi'
  word_threshold: 1
  max_seq_length: 200

  PAD_ID: 0
  UNK_ID: 1
  START_ID: 2
  EOS_ID: 3

model:
  batch_size: 32
  num_layers: 3
  model_dim: 128
  num_heads: 4
  linear_key_dim: 32
  linear_value_dim: 32
  ffn_dim: 256
  dropout: 0.2

train:
  learning_rate: 0.0001
  optimizer: 'Adam'

  train_steps: 100000
  model_dir: 'logs/iwslt15_en-vi'

  save_checkpoints_steps: 1000
  check_hook_n_iter: 100
  min_eval_frequency: 2000

  print_verbose: False
  debug: False

slack:
  webhook_url: ""
